const express = require('express');
const PDFDocument = require('pdfkit');
const Chemical = require('../models/Chemical');
const { authenticate, authorize } = require('../middleware/authMiddleware');
const { PERMISSIONS } = require('../config/roles');

const router = express.Router();

// Get Safety Dashboard Overview
router.get('/dashboard', authenticate, async (req, res) => {
  try {
    const total = await Chemical.countDocuments({ archived: false });
    const restricted = await Chemical.countDocuments({ restricted_access: true, archived: false });
    const needsTraining = await Chemical.countDocuments({ training_required: true, archived: false });
    const sdsPending = await Chemical.countDocuments({ 
        $or: [
            { sds_attached: false },
            { "sds_docs.verification_status": "Pending" }
        ],
        archived: false 
    });
    
    // Hazard distribution
    const hazards = await Chemical.aggregate([
      { $match: { archived: false } },
      { $unwind: { path: "$ghs_classes", preserveNullAndEmptyArrays: false } },
      { $group: { _id: "$ghs_classes", count: { $sum: 1 } } }
    ]);

    // Risk levels
    const risks = await Chemical.aggregate([
      { $match: { archived: false } },
      { $group: { _id: "$exposure_details.risk_level", count: { $sum: 1 } } }
    ]);

    res.json({
      summary: {
        total,
        restricted,
        needsTraining,
        sdsPending
      },
      hazards,
      risks
    });
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch safety dashboard data' });
  }
});

// Check Storage Incompatibility for a specific location
router.get('/check-incompatibility/:location', authenticate, async (req, res) => {
  try {
    const { location } = req.params;
    const chemicals = await Chemical.find({ location, archived: false });
    
    if (chemicals.length < 2) return res.json({ incompatible: false, conflicts: [] });
    
    const conflicts = [];
    const incompatiblePairs = [
      ['Acid', 'Base'],
      ['Flammable', 'Oxidizer'],
      ['Acid', 'Oxidizer'],
      ['Base', 'Oxidizer'],
      ['Water-Reactive', 'Moisture'] // Specialized check
    ];

    for (let i = 0; i < chemicals.length; i++) {
      for (let j = i + 1; j < chemicals.length; j++) {
        const c1 = chemicals[i];
        const c2 = chemicals[j];
        
        // Family-based check
        for (let pair of incompatiblePairs) {
          if (pair.includes(c1.chemical_family) && pair.includes(c2.chemical_family) && c1.chemical_family !== c2.chemical_family) {
            conflicts.push({
              chemicals: [c1.name, c2.name],
              reason: `Incompatible families: ${c1.chemical_family} and ${c2.chemical_family}`,
              severity: 'High'
            });
          }
        }
        
        // Explicit incompatibility check
        if (c1.incompatibility?.includes(c2.name) || c1.incompatibility?.includes(c2.chemical_family)) {
            conflicts.push({
                chemicals: [c1.name, c2.name],
                reason: `${c1.name} is explicitly incompatible with ${c2.name}/${c2.chemical_family}`,
                severity: 'Critical'
            });
        }
      }
    }
    
    res.json({
      incompatible: conflicts.length > 0,
      conflicts
    });
  } catch (err) {
    res.status(500).json({ error: 'Incompatibility check failed' });
  }
});

// Global Incompatibility Matrix (Rules)
router.get('/matrix', authenticate, async (req, res) => {
    // This could be stored in DB, but for now we provide a static matrix
    const matrix = [
        { family: 'Acid', incompatibleWith: ['Base', 'Oxidizer', 'Flammable Solids', 'Cyanides'] },
        { family: 'Base', incompatibleWith: ['Acid', 'Oxidizer', 'Flammable Liquids'] },
        { family: 'Oxidizer', incompatibleWith: ['Flammable Liquids', 'Flammable Solids', 'Reducing Agents', 'Acids'] },
        { family: 'Flammable', incompatibleWith: ['Oxidizer', 'Pyrophorics'] },
        { family: 'Water-Reactive', incompatibleWith: ['Aqueous Solutions', 'Acids'] }
    ];
    res.json(matrix);
});

// GET: Export SDS PDF
router.get('/export-sds/:id', authenticate, async (req, res) => {
  try {
    const chemical = await Chemical.findOne({ id: req.params.id });

    if (!chemical) {
      return res.status(404).json({ error: "Chemical not found" });
    }

    const doc = new PDFDocument({ margin: 50 });
    let filename = `SDS_${chemical.name.replace(/\s+/g, '_')}.pdf`;
    
    res.setHeader('Content-disposition', `attachment; filename="${filename}"`);
    res.setHeader('Content-type', 'application/pdf');

    // Header
    doc.fillColor('#000000').fontSize(20).text('SAFETY DATA SHEET', { align: 'center' });
    doc.fontSize(10).text(`Generated by CIMS Protocol v1.2`, { align: 'center' });
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // Section 1: Identification
    doc.fillColor('#1e40af').fontSize(14).text('SECTION 1: IDENTIFICATION');
    doc.fillColor('#000000').fontSize(10).moveDown(0.5);
    doc.text(`Product Name: ${chemical.name}`);
    doc.text(`CAS Number: ${chemical.cas_number || 'N/A'}`);
    doc.text(`Chemical Formula: ${chemical.formula || 'N/A'}`);
    doc.text(`Family: ${chemical.chemical_family || 'General'}`);
    doc.moveDown();

    // Section 2: Hazard Identification
    doc.fillColor('#1e40af').fontSize(14).text('SECTION 2: HAZARD IDENTIFICATION');
    doc.fillColor('#000000').fontSize(10).moveDown(0.5);
    doc.text(`Signal Word: ${chemical.ghs_hazards?.signal_word || 'None'}`);
    doc.text(`Hazard Statements: ${chemical.ghs_hazards?.h_codes?.join(', ') || 'None assigned'}`);
    doc.text(`Precautionary Statements: ${chemical.ghs_hazards?.p_codes?.join(', ') || 'None assigned'}`);
    doc.moveDown();

    // Section 4: First Aid
    doc.fillColor('#1e40af').fontSize(14).text('SECTION 4: FIRST AID MEASURES');
    doc.fillColor('#000000').fontSize(10).moveDown(0.5);
    doc.text(`${chemical.emergency_response?.first_aid || chemical.emergency_instructions || 'Consult medical professional.'}`, { align: 'justify' });
    doc.moveDown();

    // Section 8: Exposure Controls / PPE
    doc.fillColor('#1e40af').fontSize(14).text('SECTION 8: EXPOSURE CONTROLS / PERSONAL PROTECTION');
    doc.fillColor('#000000').fontSize(10).moveDown(0.5);
    doc.text(`Required PPE: ${chemical.ppe_requirements?.join(', ') || 'Standard Lab PPE'}`);
    doc.text(`Ventilation: ${chemical.exposure_details?.fume_hood_required ? 'Fume Hood Mandatory' : 'Standard Ventilation'}`);
    doc.text(`Exposure Limits: ${chemical.exposure_details?.exposure_limits || 'Not established'}`);
    doc.moveDown();

    // Footer
    doc.fontSize(8).fillColor('#9ca3af').text(`End of Safety Data Sheet - Authorized by CIMS Safety Engine`, 50, doc.page.height - 50, { align: 'center' });

    doc.pipe(res);
    doc.end();

  } catch (err) {
    console.error("SDS Export Error:", err);
    res.status(500).json({ error: "Failed to generate SDS PDF" });
  }
});

module.exports = router;


