const PERMISSIONS = {
  CREATE_CHEMICAL: 'create_chemical',
  EDIT_CHEMICAL: 'edit_chemical',
  DELETE_CHEMICAL: 'delete_chemical',
  APPROVE_REQUEST: 'approve_request',
  VIEW_REPORTS: 'view_reports',
  VIEW_AUDIT_LOGS: 'view_audit_logs',
  ASSIGN_ROLES: 'assign_roles',
  VIEW_CHEMICALS: 'view_chemicals',
  SUBMIT_REQUEST: 'submit_request',
  UPDATE_STOCK: 'update_stock',
  VIEW_SAFETY_INFO: 'view_safety_info',
  MANAGE_SETTINGS: 'manage_settings'
};

const ROLES = {
  ADMIN: 'Admin',
  LAB_MANAGER: 'Lab Manager',
  LAB_TECHNICIAN: 'Lab Technician',
  SAFETY_OFFICER: 'Safety Officer',
  VIEWER: 'Viewer / Auditor'
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.LAB_MANAGER]: [
    PERMISSIONS.CREATE_CHEMICAL,
    PERMISSIONS.EDIT_CHEMICAL,
    PERMISSIONS.APPROVE_REQUEST,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_CHEMICALS,
    PERMISSIONS.SUBMIT_REQUEST,
    PERMISSIONS.UPDATE_STOCK,
    PERMISSIONS.VIEW_SAFETY_INFO
  ],
  [ROLES.LAB_TECHNICIAN]: [
    PERMISSIONS.VIEW_CHEMICALS,
    PERMISSIONS.UPDATE_STOCK,
    PERMISSIONS.SUBMIT_REQUEST,
  ],
  [ROLES.SAFETY_OFFICER]: [
    PERMISSIONS.VIEW_CHEMICALS,
    PERMISSIONS.VIEW_SAFETY_INFO,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.VIEW_CHEMICALS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ]
};

module.exports = { PERMISSIONS, ROLES, ROLE_PERMISSIONS };


