const PERMISSIONS = {
  CREATE_CHEMICAL: 'create_chemical',
  EDIT_CHEMICAL: 'edit_chemical',
  DELETE_CHEMICAL: 'delete_chemical',
  APPROVE_REQUEST: 'approve_request',
  VIEW_REPORTS: 'view_reports',
  VIEW_AUDIT_LOGS: 'view_audit_logs',
  ASSIGN_ROLES: 'assign_roles',
  VIEW_CHEMICALS: 'view_chemicals',
  SUBMIT_REQUEST: 'submit_request',
  UPDATE_STOCK: 'update_stock',
  VIEW_SAFETY_INFO: 'view_safety_info',
  MANAGE_SETTINGS: 'manage_settings',
  MANAGE_USERS: 'manage_users',
  MANAGE_WASTE: 'manage_waste',
  APPROVE_DISPOSAL: 'approve_disposal',
  PERFORM_BACKUP: 'perform_backup',
  PERFORM_RESTORE: 'perform_restore',
  MANAGE_SECURITY: 'manage_security',
  VIEW_FINANCIALS: 'view_financials',
  MANAGE_LABS: 'MANAGE_LABS',
  APPROVE_CROSS_LAB_TRANSFER: 'approve_cross_lab_transfer'
};

const ROLES = {
  ADMIN: 'Admin',
  LAB_MANAGER: 'Lab Manager',
  SAFETY_OFFICER: 'Safety Officer',
  PROCUREMENT_OFFICER: 'Procurement Officer',
  LAB_STAFF: 'Laboratory Staff',
  AUDITOR: 'Viewer / Auditor'
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.LAB_MANAGER]: [
    PERMISSIONS.CREATE_CHEMICAL,
    PERMISSIONS.EDIT_CHEMICAL,
    PERMISSIONS.APPROVE_REQUEST,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_CHEMICALS,
    PERMISSIONS.SUBMIT_REQUEST,
    PERMISSIONS.UPDATE_STOCK,
    PERMISSIONS.VIEW_SAFETY_INFO,
    PERMISSIONS.MANAGE_WASTE,
    PERMISSIONS.APPROVE_DISPOSAL,
    PERMISSIONS.APPROVE_CROSS_LAB_TRANSFER
  ],
  [ROLES.SAFETY_OFFICER]: [
    PERMISSIONS.VIEW_CHEMICALS,
    PERMISSIONS.VIEW_SAFETY_INFO,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_WASTE,
    PERMISSIONS.APPROVE_DISPOSAL
  ],
  [ROLES.PROCUREMENT_OFFICER]: [
    PERMISSIONS.VIEW_CHEMICALS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.SUBMIT_REQUEST
  ],
  [ROLES.LAB_STAFF]: [
    PERMISSIONS.VIEW_CHEMICALS,
    PERMISSIONS.UPDATE_STOCK,
    PERMISSIONS.SUBMIT_REQUEST
  ],
  [ROLES.AUDITOR]: [
    PERMISSIONS.VIEW_CHEMICALS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_SAFETY_INFO,
    PERMISSIONS.UPDATE_STOCK
  ]
};

module.exports = { PERMISSIONS, ROLES, ROLE_PERMISSIONS };


